### ISSUE TITLE
Improve Lighthouse metrics for homepage & sub pages

### ISSUE THREAD

**Issue by onmax** [nimiq/nimiq-website#101]
**Description**

I'd like to take our performance, accessibility and SEO to the next level by:

1. **Auditing Lighthouse Scores**.
   - **Home page (most critical):** https://page-speed.dev/www.nimiq.com
   - **Other key pages:** `/about', `/wallet`, `/blog`, etc.

2. **Optimise based on findings**.
   - Compress and lazy-load images
   - Split and cache JS/CSS(?)
   - Add `alt` to images

3. **Automating Lighthouse runs in CI**. (optional)
   - Add a GitHub Action or Lighthouse CI Step
   - Enforce score thresholds (e.g. Performance ≥ 90, Accessibility ≥ 90, SEO ≥ 90, Best Practices ≥ 90)

> **Example CI snippet**  
```yaml
name: "Lighthouse CI"
on:
  push:
    branches: [ main ]
jobs:
  lighthouse-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: treosh/lighthouse-ci-action@v7
        with:
          configPath: "./lighthouserc.json"
```
---
