### ISSUE TITLE
Update og image for home page

### ISSUE THREAD

**Issue by onmax** [nimiq/nimiq-website#92]
In `[...uid].vue`, we should have a new special case:

![Image](https://github.com/user-attachments/assets/52631b9e-1e45-41b0-8f9a-382c374262a3)

WE need to convert this css to tw classes

- font family mulish

```css
h1 {
  font-size: 96px;
  margin-top: 92px;
  font-weight: bold;
  color: white;
  line-height: 1.5;
}

p {
  color: rgba(255, 255, 255, 0.4); /* white at 40% opacity */
  font-size: 40px;
  margin-top: 0;
  line-height: 1.3;
}
```

 
<details><summary>Previous image</summary>
<p>

![Image](https://github.com/user-attachments/assets/3d35da57-f2e1-4937-9530-0abaff6c490d)

</p>
</details>
